# Generated by Django 2.1.7 on 2019-03-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190320_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubro',
            name='image',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
